const express = require('express');
const crypto = require('crypto');
const db = require('../db');
const { requireAdmin } = require('../auth');
const router = express.Router();
const clean = v => String(v == null ? '' : v).trim();
const n = v => Math.max(0, Number(v) || 0);
const fail = (res, errors) => res.status(400).json({ error: 'Import validation failed', errors });
router.post('/:kind', requireAdmin, (req,res) => {
 const kind=req.params.kind, rows=Array.isArray(req.body?.rows)?req.body.rows:[]; if(!rows.length)return fail(res,['No rows found in CSV']);
 const errors=[]; rows.forEach((r,i)=>{if(kind==='inventory'&&(!clean(r.name)||r.price===''||r.quantity===''))errors.push(`Row ${i+2}: name, price and quantity are required`); if(kind==='customers'&&(!clean(r.name)||!clean(r.phone)))errors.push(`Row ${i+2}: name and phone are required`); if(kind==='sales'&&(!clean(r.date)||!clean(r.item)||r.quantity===''||r.amount===''))errors.push(`Row ${i+2}: date, item, quantity and amount are required`);}); if(errors.length)return fail(res,errors.slice(0,25));
 if(kind==='inventory'){const inv=db.getInventory(); let added=0,updated=0; rows.forEach(r=>{const code=clean(r.code), existing=inv.find(x=>(code&&x.code===code)||x.name.toLowerCase()===clean(r.name).toLowerCase()); if(existing){existing.quantity+=n(r.quantity);existing.price=n(r.price)||existing.price; existing.category=clean(r.category)||existing.category; existing.supplier=clean(r.supplier)||existing.supplier;updated++;}else{inv.push({id:'ITM-'+crypto.randomBytes(4).toString('hex').toUpperCase(),name:clean(r.name),code:code||null,category:clean(r.category)||'Uncategorized',supplier:clean(r.supplier),price:n(r.price),costPrice:n(r.costPrice),quantity:n(r.quantity),shortDescription:'',detailedDescription:'',createdAt:Date.now(),frequent:String(r.frequent).toLowerCase()==='true'});added++;}});db.setInventory(inv);return res.json({ok:true,added,updated});}
 if(kind==='customers'){const rowsDb=db.getCustomers();let added=0,updated=0;rows.forEach(r=>{const phone=clean(r.phone).replace(/\D/g,'');let x=rowsDb.find(c=>c.phone===phone);if(x){Object.assign(x,{name:clean(r.name),email:clean(r.email),address:clean(r.address)});updated++;}else{rowsDb.push({id:'CUS-'+crypto.randomBytes(4).toString('hex').toUpperCase(),name:clean(r.name),phone,email:clean(r.email),address:clean(r.address),createdAt:Date.now()});added++;}});db.setCustomers(rowsDb);return res.json({ok:true,added,updated});}
 const sales=db.getSales(); let added=0; rows.forEach(r=>{const stamp=Date.parse(`${clean(r.date)}T${clean(r.time)||'12:00'}`); const amount=n(r.amount); const sale={id:'SALE-IMP-'+crypto.randomBytes(4).toString('hex').toUpperCase(),timestamp:isNaN(stamp)?Date.now():stamp,items:[{id:'IMPORTED-'+added,name:clean(r.item),qty:n(r.quantity),price:amount/Math.max(1,n(r.quantity)),lineSubtotal:amount,lineTotal:amount,costPriceAtSale:0,lineProfit:0}],subtotal:amount,discountAmount:0,discountPercent:0,total:amount,paymentMethod:'cash',amountPaid:amount,amountDue:0,customerName:clean(r.customerName),customerPhone:'',customerAddress:'',paymentHistory:[],returns:[],imported:true}; if(!sales.some(x=>x.timestamp===sale.timestamp&&x.customerName===sale.customerName&&x.total===sale.total)) {sales.push(sale);added++;}}); db.setSales(sales);return res.json({ok:true,added,updated:0});
});
module.exports=router;
